blank_issues_enabled: false
contact_links:
  - name: Сообщить об уязвимости
    url: https://github.com/baglayradik/Gatewire/security/advisories/new
    about: Пожалуйста, сообщайте об уязвимостях приватно, а не через публичные issue.
